# Generated by Django 5.2.17 on 2026-09-28 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("telegram", "تيليجرام"),
                            ("whatsapp", "واتساب"),
                            ("push", "إشعارات المتصفح"),
                            ("newsletter", "النشرة البريدية"),
                        ],
                        max_length=12,
                        unique=True,
                        verbose_name="القناة",
                    ),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="مفعّلة")),
                (
                    "auto_kinds",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="فارغة = كل الأنواع (حسب خيارات كل مادة).",
                        verbose_name="أنواع المواد التي تُرسل تلقائياً",
                    ),
                ),
                (
                    "breaking_only",
                    models.BooleanField(default=False, verbose_name="العاجل فقط"),
                ),
                (
                    "telegram_chat_ids",
                    models.CharField(
                        blank=True,
                        help_text="مثل \u200e@my_channel\u200e أو \u200e-100123…\u200e مفصولة بفواصل",
                        max_length=500,
                        verbose_name="معرّفات القنوات",
                    ),
                ),
                (
                    "with_image",
                    models.BooleanField(
                        default=True, verbose_name="إرسال الصورة مع الخبر"
                    ),
                ),
                (
                    "silent_hours",
                    models.CharField(
                        blank=True,
                        help_text="مثل 0-6 : يُرسل بلا صوت تنبيه في هذه الساعات",
                        max_length=20,
                        verbose_name="ساعات الإرسال الصامت",
                    ),
                ),
                (
                    "whatsapp_template",
                    models.CharField(
                        blank=True,
                        help_text="قالب بمتغيرين: العنوان والرابط",
                        max_length=80,
                        verbose_name="اسم قالب واتساب المعتمد",
                    ),
                ),
                (
                    "whatsapp_language",
                    models.CharField(
                        default="ar", max_length=10, verbose_name="لغة القالب"
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        blank=True,
                        default="{kicker}<b>{title}</b>\n\n{summary}\n\n{url}",
                        help_text="المتغيرات: {title} {summary} {url} {kicker} {category}",
                        verbose_name="قالب الرسالة",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعداد قناة",
                "verbose_name_plural": "إعدادات القنوات",
            },
        ),
        migrations.CreateModel(
            name="NewsletterIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("subject", models.CharField(max_length=200)),
                ("html", models.TextField()),
                ("text", models.TextField()),
                ("article_ids", models.JSONField(default=list)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("token", models.CharField(editable=False, max_length=48, unique=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(max_length=700, unique=True)),
                ("p256dh", models.CharField(max_length=200)),
                ("auth", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("failures", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("topics", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="بصيغة 9705xxxxxxxx دون +",
                        max_length=20,
                        unique=True,
                        verbose_name="رقم الهاتف الدولي",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80)),
                (
                    "opted_in_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("source", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["-opted_in_at"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("telegram", "تيليجرام"),
                            ("whatsapp", "واتساب"),
                            ("push", "إشعارات المتصفح"),
                            ("newsletter", "النشرة البريدية"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "في الطابور"),
                            ("sent", "أُرسلت"),
                            ("failed", "فشلت"),
                            ("skipped", "تُخطّيت"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("recipients", models.PositiveIntegerField(default=0)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("external_id", models.CharField(blank=True, max_length=120)),
                ("error", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="content.article",
                    ),
                ),
                (
                    "breaking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="content.breakingnews",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
