# Generated by Django 5.2.17 on 2026-09-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distribution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelconfig",
            name="channel",
            field=models.CharField(
                choices=[
                    ("telegram", "تيليجرام"),
                    ("whatsapp", "واتساب"),
                    ("push", "إشعارات المتصفح"),
                    ("newsletter", "النشرة البريدية"),
                    ("facebook", "صفحة فيسبوك"),
                    ("x", "إكس"),
                ],
                max_length=12,
                unique=True,
                verbose_name="القناة",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="channel",
            field=models.CharField(
                choices=[
                    ("telegram", "تيليجرام"),
                    ("whatsapp", "واتساب"),
                    ("push", "إشعارات المتصفح"),
                    ("newsletter", "النشرة البريدية"),
                    ("facebook", "صفحة فيسبوك"),
                    ("x", "إكس"),
                ],
                db_index=True,
                max_length=12,
            ),
        ),
    ]
