# Generated by Django 5.2.17 on 2026-09-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_session_epoch"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                help_text="بريد عند إرسال مادة للمراجعة أو إعادتها أو اعتمادها أو نشرها.",
                verbose_name="تنبيهات البريد",
            ),
        ),
    ]
