# Generated by Django 5.2.17 on 2026-09-29 06:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_email_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="keys_only",
            field=models.BooleanField(
                default=False,
                help_text="لا يُقبل رمز التطبيق عند الدخول، بل مفتاح الأمان (ورموز الاسترداد للطوارئ).",
                verbose_name="مفتاح الأمان فقط",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="webauthn_handle",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.CreateModel(
            name="SecurityKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="الاسم")),
                ("credential_id", models.CharField(max_length=1400, unique=True)),
                ("public_key", models.BinaryField()),
                ("sign_count", models.BigIntegerField(default=0)),
                ("aaguid", models.CharField(blank=True, max_length=36)),
                ("transports", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مفتاح أمان",
                "verbose_name_plural": "مفاتيح الأمان",
                "ordering": ["created_at"],
            },
        ),
    ]
