# Generated by Django 5.2.17 on 2026-09-28 18:56

import arcms.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("news", "خبر"),
                            ("report", "تقرير"),
                            ("investigation", "تحقيق"),
                            ("interview", "حوار"),
                            ("opinion", "مقال رأي"),
                            ("blog", "تدوينة"),
                            ("translation", "ترجمة"),
                            ("video", "فيديو"),
                            ("infographic", "إنفوجراف"),
                            ("gallery", "معرض صور"),
                            ("cartoon", "كاريكاتير"),
                        ],
                        default="news",
                        max_length=20,
                        verbose_name="نوع المادة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("in_review", "بانتظار المراجعة"),
                            ("changes", "أُعيدت للتعديل"),
                            ("approved", "معتمدة للنشر"),
                            ("scheduled", "مجدولة"),
                            ("published", "منشورة"),
                            ("unpublished", "مسحوبة"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "kicker",
                    models.CharField(
                        blank=True,
                        help_text="مثل: خاص، فيديو، ترجمة",
                        max_length=60,
                        verbose_name="سطر فوق العنوان",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="العنوان")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="العنوان الفرعي"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="يظهر في القوائم ونتائج البحث والمشاركة.",
                        verbose_name="الملخص",
                    ),
                ),
                (
                    "dateline",
                    models.CharField(
                        blank=True,
                        help_text="مثل: غزة - خاص",
                        max_length=80,
                        verbose_name="مكان الخبر",
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="المتن")),
                (
                    "slug",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, verbose_name="الرابط"
                    ),
                ),
                (
                    "image_caption",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="تعليق الصورة"
                    ),
                ),
                (
                    "hide_featured_image",
                    models.BooleanField(
                        default=False, verbose_name="إخفاء الصورة في صفحة المادة"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="يوتيوب أو فيميو أو فيسبوك",
                        verbose_name="رابط الفيديو",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=150, verbose_name="المصدر"),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="رابط المصدر")),
                (
                    "source_notes",
                    arcms.core.fields.EncryptedTextField(
                        blank=True,
                        help_text="لا تظهر للجمهور أبداً، ولا يراها إلا كاتب المادة ورئيس التحرير.",
                        verbose_name="ملاحظات المصادر (سرّية ومشفّرة)",
                    ),
                ),
                (
                    "correction",
                    models.TextField(
                        blank=True,
                        help_text="يظهر أسفل المادة إن وُجد.",
                        verbose_name="تصحيح منشور",
                    ),
                ),
                (
                    "is_breaking",
                    models.BooleanField(default=False, verbose_name="عاجل"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="في الواجهة"),
                ),
                (
                    "is_exclusive",
                    models.BooleanField(default=False, verbose_name="خاص"),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=0,
                        help_text="الأعلى يتقدّم في الواجهة.",
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "featured_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="في الواجهة حتى"
                    ),
                ),
                (
                    "allow_indexing",
                    models.BooleanField(
                        default=True, verbose_name="السماح لمحركات البحث"
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان محركات البحث"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="وصف محركات البحث"
                    ),
                ),
                (
                    "send_telegram",
                    models.BooleanField(default=True, verbose_name="تيليجرام"),
                ),
                (
                    "send_whatsapp",
                    models.BooleanField(default=False, verbose_name="واتساب"),
                ),
                (
                    "send_push",
                    models.BooleanField(default=False, verbose_name="إشعار فوري"),
                ),
                (
                    "in_newsletter",
                    models.BooleanField(default=True, verbose_name="في النشرة اليومية"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="أُنشئت"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر حفظ"),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="موعد النشر"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="تاريخ النشر"
                    ),
                ),
                ("first_published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تحديث للمحتوى"
                    ),
                ),
                ("distributed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="المشاهدات"),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("legacy_url", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأها",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related",
                    models.ManyToManyField(
                        blank=True, to="content.article", verbose_name="مواد ذات صلة"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة",
                "verbose_name_plural": "المواد",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", arcms.core.fields.EncryptedTextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="العنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=160, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="التقديم")),
                (
                    "color",
                    models.CharField(blank=True, max_length=7, verbose_name="اللون"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "ملف خاص",
                "verbose_name_plural": "الملفات الخاصة",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="العنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=160, unique=True
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="المحتوى")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منشورة"),
                ),
                (
                    "show_contact_form",
                    models.BooleanField(
                        default=False, verbose_name="إظهار نموذج التواصل"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "صفحة",
                "verbose_name_plural": "الصفحات الثابتة",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="الوسم")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=100, unique=True
                    ),
                ),
                (
                    "normalized",
                    models.CharField(editable=False, max_length=80, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "وسم",
                "verbose_name_plural": "الوسوم",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SearchDocument",
            fields=[
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="search_doc",
                        serialize=False,
                        to="content.article",
                    ),
                ),
                ("title_terms", models.TextField(blank=True)),
                ("lead_terms", models.TextField(blank=True)),
                ("body_terms", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArticleLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heartbeat_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock",
                        to="content.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("in_review", "بانتظار المراجعة"),
                            ("changes", "أُعيدت للتعديل"),
                            ("approved", "معتمدة للنشر"),
                            ("scheduled", "مجدولة"),
                            ("published", "منشورة"),
                            ("unpublished", "مسحوبة"),
                        ],
                        max_length=12,
                    ),
                ),
                ("data", models.JSONField()),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="content.article",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=140, unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="مثل: مراسل، كاتب وباحث",
                        max_length=120,
                        verbose_name="الصفة",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="نبذة")),
                (
                    "x_handle",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="حساب إكس"
                    ),
                ),
                (
                    "is_columnist",
                    models.BooleanField(default=False, verbose_name="كاتب رأي"),
                ),
                (
                    "show_page",
                    models.BooleanField(default=True, verbose_name="صفحة عامة"),
                ),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب الطاقم",
                    ),
                ),
            ],
            options={
                "verbose_name": "كاتب",
                "verbose_name_plural": "الكتّاب",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="content.author",
                verbose_name="الكتّاب",
            ),
        ),
        migrations.CreateModel(
            name="BreakingNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=280, verbose_name="نص العاجل")),
                (
                    "link",
                    models.CharField(blank=True, max_length=300, verbose_name="رابط"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ينتهي"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ظاهر")),
                (
                    "send_telegram",
                    models.BooleanField(default=True, verbose_name="تيليجرام"),
                ),
                (
                    "send_push",
                    models.BooleanField(default=True, verbose_name="إشعار فوري"),
                ),
                (
                    "send_whatsapp",
                    models.BooleanField(default=False, verbose_name="واتساب"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.article",
                        verbose_name="المادة المرتبطة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "خبر عاجل",
                "verbose_name_plural": "العاجل",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="الاسم")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="الرابط",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="لون القسم"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "legacy_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "desk_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="desks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طاقم القسم",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="content.category",
                        verbose_name="القسم الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="content.category",
                verbose_name="القسم",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="extra_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="extra_articles",
                to="content.category",
                verbose_name="أقسام إضافية",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="dossiers",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="content.dossier",
                verbose_name="الملفات الخاصة",
            ),
        ),
        migrations.CreateModel(
            name="EditorialNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("kind", models.CharField(default="comment", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="content.article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=160, unique=True
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="التقديم")),
                (
                    "is_live",
                    models.BooleanField(default=True, verbose_name="جارية الآن"),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.category",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تغطية مباشرة",
                "verbose_name_plural": "التغطيات المباشرة",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "صورة")], default="image", max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to="uploads/%Y/%m/", verbose_name="الملف"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="العنوان"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="النص البديل"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="التعليق"
                    ),
                ),
                (
                    "credit",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="المصدر/المصوّر"
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("mime", models.CharField(blank=True, max_length=60)),
                ("size", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("renditions", models.JSONField(blank=True, default=dict)),
                (
                    "removed_metadata",
                    models.JSONField(
                        blank=True, default=list, verbose_name="البيانات المنزوعة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "legacy_url",
                    models.URLField(blank=True, db_index=True, max_length=500),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "وسيط",
                "verbose_name_plural": "مكتبة الوسائط",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="النص")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="مهم"),
                ),
                ("is_pinned", models.BooleanField(default=False, verbose_name="مثبّت")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coverage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="content.livecoverage",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="livecoverage",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.mediaasset",
                verbose_name="الغلاف",
            ),
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=400)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_items",
                        to="content.article",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.mediaasset",
                verbose_name="الغلاف",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="content.mediaasset",
                verbose_name="الصورة",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="content.mediaasset",
                verbose_name="الصورة الرئيسية",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="gallery",
            field=models.ManyToManyField(
                blank=True,
                related_name="galleries",
                through="content.GalleryItem",
                to="content.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="content.tag",
                verbose_name="الوسوم",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "-published_at"], name="content_art_status_9dc828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["kind", "status", "-published_at"],
                name="content_art_kind_ef4a3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "status", "-published_at"],
                name="content_art_categor_1a8f08_idx",
            ),
        ),
    ]
