# Generated by Django 5.2.17 on 2026-09-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_search_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="audio",
            field=models.FileField(
                blank=True,
                help_text="MP3 أو M4A أو OGG حتى 60 ميغابايت. يُشغَّل من خادمكم دون أي منصة خارجية.",
                max_length=200,
                upload_to="audio/%Y/%m/",
                verbose_name="الملف الصوتي",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="kind",
            field=models.CharField(
                choices=[
                    ("news", "خبر"),
                    ("report", "تقرير"),
                    ("investigation", "تحقيق"),
                    ("interview", "حوار"),
                    ("opinion", "مقال رأي"),
                    ("blog", "تدوينة"),
                    ("translation", "ترجمة"),
                    ("video", "فيديو"),
                    ("infographic", "إنفوجراف"),
                    ("gallery", "معرض صور"),
                    ("cartoon", "كاريكاتير"),
                    ("podcast", "بودكاست"),
                    ("short", "فيديو قصير"),
                ],
                default="news",
                max_length=20,
                verbose_name="نوع المادة",
            ),
        ),
    ]
