# Generated by Django 5.2.17 on 2026-09-28 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_article_audio_alter_article_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                help_text="تظهر خلف عنوان صفحة القسم.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="content.mediaasset",
                verbose_name="صورة الغلاف",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="page_layout",
            field=models.CharField(
                choices=[
                    ("feed", "مادة كبيرة ثم قائمة، مع عمود جانبي"),
                    ("grid", "شبكة بطاقات بعرض الصفحة"),
                    ("magazine", "مجلة: مادة كبيرة بالعنوان على الصورة ثم شبكة"),
                ],
                default="feed",
                max_length=10,
                verbose_name="شكل صفحة القسم",
            ),
        ),
    ]
