# Generated by Django 5.2.17 on 2026-09-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_category_page_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="send_facebook",
            field=models.BooleanField(default=True, verbose_name="صفحة فيسبوك"),
        ),
        migrations.AddField(
            model_name="article",
            name="send_x",
            field=models.BooleanField(default=True, verbose_name="إكس"),
        ),
        migrations.AddField(
            model_name="breakingnews",
            name="send_x",
            field=models.BooleanField(default=False, verbose_name="إكس"),
        ),
    ]
