# Generated by Django 5.2.17 on 2026-09-29 06:48

from django.db import migrations, models


def backfill(apps, schema_editor):
    """التصحيحات السابقة تأخذ تاريخ آخر تحديث للمادة."""
    Article = apps.get_model("content", "Article")
    for a in Article.objects.exclude(correction="").only("pk", "content_updated_at", "updated_at"):
        Article.objects.filter(pk=a.pk).update(corrected_at=a.content_updated_at or a.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_social_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="corrected_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="تاريخ التصحيح"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="correction",
            field=models.TextField(
                blank=True,
                help_text="يظهر أسفل المادة وفي «سجل التصحيحات».",
                verbose_name="تصحيح منشور",
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
