# Generated by Django 5.2.17 on 2026-09-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_corrected_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="focal_x",
            field=models.FloatField(default=0.5, verbose_name="نقطة التركيز أفقياً"),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="focal_y",
            field=models.FloatField(default=0.4, verbose_name="نقطة التركيز عمودياً"),
        ),
    ]
