# Generated by Django 5.2.17 on 2026-09-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_focal_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="sensitive",
            field=models.BooleanField(
                default=False,
                help_text="دماء أو جثث أو إصابات: تُعرض في الموقع مموّهة حتى يختار القارئ رؤيتها، ولا تُستخدم في بطاقات المشاركة ولا في المنصات والنشرة.",
                verbose_name="صورة قاسية",
            ),
        ),
    ]
