# Generated by Django 5.2.17 on 2026-09-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_media_sensitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="claim",
            field=models.TextField(
                blank=True,
                help_text="نص الادعاء المتداول باختصار، كما ورد.",
                verbose_name="الادعاء",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="claim_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ ظهور الادعاء"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="claim_url",
            field=models.URLField(
                blank=True,
                help_text="يُفضَّل رابط نسخة مؤرشفة لا المنشور الأصلي، كي لا يزيد التدقيق انتشاره.",
                max_length=500,
                verbose_name="رابط الادعاء",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="claimant",
            field=models.CharField(
                blank=True,
                help_text="حساب أو صفحة أو شخص، أو «منشورات متداولة».",
                max_length=200,
                verbose_name="مصدر الادعاء",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="verdict",
            field=models.CharField(
                blank=True,
                choices=[
                    ("false", "زائف"),
                    ("misleading", "مضلل"),
                    ("context", "خارج السياق"),
                    ("unproven", "غير مثبت"),
                    ("partly", "صحيح جزئياً"),
                    ("true", "صحيح"),
                    ("satire", "ساخر"),
                ],
                max_length=12,
                verbose_name="الحكم",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="kind",
            field=models.CharField(
                choices=[
                    ("news", "خبر"),
                    ("report", "تقرير"),
                    ("investigation", "تحقيق"),
                    ("interview", "حوار"),
                    ("opinion", "مقال رأي"),
                    ("blog", "تدوينة"),
                    ("translation", "ترجمة"),
                    ("video", "فيديو"),
                    ("infographic", "إنفوجراف"),
                    ("gallery", "معرض صور"),
                    ("cartoon", "كاريكاتير"),
                    ("podcast", "بودكاست"),
                    ("short", "فيديو قصير"),
                    ("factcheck", "تدقيق معلومات"),
                ],
                default="news",
                max_length=20,
                verbose_name="نوع المادة",
            ),
        ),
    ]
