# Generated by Django 5.2.17 on 2026-09-28 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "قيد الإنشاء"),
                            ("ok", "مكتملة"),
                            ("failed", "فشلت"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("key_fingerprint", models.CharField(blank=True, max_length=32)),
                ("includes_media", models.BooleanField(default=True)),
                ("trigger", models.CharField(default="manual", max_length=20)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
