# Generated by Django 5.2.17 on 2026-09-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprecord",
            name="offsite_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backuprecord",
            name="offsite_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="backuprecord",
            name="offsite_key",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="backuprecord",
            name="offsite_status",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
