# Generated by Django 5.2.17 on 2026-09-28 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=150)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إنشاء"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                            ("login", "دخول"),
                            ("login_failed", "محاولة دخول فاشلة"),
                            ("logout", "خروج"),
                            ("2fa", "التحقق الثنائي"),
                            ("workflow", "سير العمل"),
                            ("publish", "نشر"),
                            ("unpublish", "سحب"),
                            ("distribute", "توزيع"),
                            ("settings", "إعدادات"),
                            ("backup", "نسخ احتياطي"),
                            ("import", "استيراد"),
                            ("security", "أمان"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, db_index=True, max_length=60),
                ),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("prev_hash", models.CharField(blank=True, max_length=64)),
                ("hash", models.CharField(max_length=64, unique=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "قيد تدقيق",
                "verbose_name_plural": "سجل التدقيق",
                "ordering": ["-id"],
            },
        ),
    ]
