# Generated by Django 5.2.17 on 2026-09-28 20:51

import arcms.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(max_length=12, unique=True, verbose_name="المرجع"),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                (
                    "subject",
                    arcms.core.fields.EncryptedTextField(
                        blank=True, verbose_name="الموضوع"
                    ),
                ),
                ("body", arcms.core.fields.EncryptedTextField(verbose_name="المعلومة")),
                (
                    "contact",
                    arcms.core.fields.EncryptedTextField(
                        blank=True, verbose_name="وسيلة التواصل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("reviewing", "قيد التحقق"),
                            ("used", "بُني عليه عمل صحفي"),
                            ("closed", "مغلق"),
                            ("spam", "مزعج"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "note",
                    arcms.core.fields.EncryptedTextField(
                        blank=True, verbose_name="ملاحظة داخلية"
                    ),
                ),
                ("unread", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المتابِع",
                    ),
                ),
            ],
            options={
                "verbose_name": "بلاغ",
                "verbose_name_plural": "البلاغات",
                "ordering": ["-unread", "-updated_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="TipMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_source", models.BooleanField(default=True)),
                ("body", arcms.core.fields.EncryptedTextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tips.tip",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TipAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "صورة"), ("pdf", "مستند PDF")], max_length=8
                    ),
                ),
                ("mime", models.CharField(max_length=40)),
                ("ext", models.CharField(max_length=8)),
                ("size", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "removed",
                    models.JSONField(
                        blank=True, default=list, verbose_name="ما نُزع منها"
                    ),
                ),
                ("ciphertext", models.BinaryField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tips.tip",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tips.tipmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
