# Generated by Django 5.2.17 on 2026-09-29 06:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0005_social_channels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WireKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="الكلمة أو العبارة"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "كلمة تنبيه",
                "verbose_name_plural": "كلمات التنبيه",
                "ordering": ["word"],
            },
        ),
        migrations.CreateModel(
            name="WireSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثل: وكالة الأنباء الرسمية — الأخبار المحلية",
                        max_length=120,
                        verbose_name="اسم المصدر",
                    ),
                ),
                (
                    "feed_url",
                    models.URLField(
                        max_length=500, verbose_name="رابط الخلاصة (RSS أو Atom)"
                    ),
                ),
                (
                    "credit",
                    models.CharField(
                        blank=True,
                        help_text="يُكتب في حقل «المصدر» للمادة المعتمدة. إن تُرك فارغاً يُستخدم اسم المصدر.",
                        max_length=120,
                        verbose_name="نص النسبة في المادة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "poll_minutes",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="الجلب كل (دقائق)"
                    ),
                ),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("last_ok_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                ("etag", models.CharField(blank=True, max_length=200)),
                ("modified", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.category",
                        verbose_name="القسم الافتراضي للمسودة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مصدر وكالة",
                "verbose_name_plural": "مصادر الوكالات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WireItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid_hash", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("link", models.URLField(blank=True, max_length=1000)),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fetched_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("search_text", models.TextField(blank=True)),
                ("is_alert", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("adopted", "اعتُمد"),
                            ("ignored", "تُجوهل"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=10,
                    ),
                ),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.article",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="wires.wiresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة وكالة",
                "verbose_name_plural": "مواد الوكالات",
                "ordering": ["-published_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_at"], name="wire_status_pub"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "guid_hash"), name="wire_item_unique_guid"
                    )
                ],
            },
        ),
    ]
