# Generated by Django 5.2.17 on 2026-09-29 06:52

import arcms.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0006_corrected_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="الموضوع")),
                (
                    "brief",
                    arcms.core.fields.EncryptedTextField(
                        blank=True,
                        help_text="الزاوية المطلوبة، والمصادر المقترحة، وما يلزم من صور أو فيديو. مشفّر في القاعدة ولا يظهر للجمهور.",
                        verbose_name="التوجيه",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        default="news", max_length=20, verbose_name="نوع المادة"
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="الموعد النهائي"
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        choices=[(0, "عادية"), (1, "مهمة"), (2, "عاجلة")],
                        default=0,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "فكرة"),
                            ("assigned", "مكلَّفة"),
                            ("working", "قيد العمل"),
                            ("filed", "سُلّمت"),
                            ("done", "نُشرت"),
                            ("dropped", "أُلغيت"),
                        ],
                        db_index=True,
                        default="idea",
                        max_length=10,
                        verbose_name="المرحلة",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="content.article",
                        verbose_name="المادة",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المكلَّف",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.category",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة تغطية",
                "verbose_name_plural": "خطة التغطية",
                "ordering": ["due_at", "-priority", "created_at"],
            },
        ),
    ]
