# Generated by Django 5.2.17 on 2026-09-29 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250, verbose_name="السؤال")),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="توضيح"),
                ),
                (
                    "is_open",
                    models.BooleanField(default=True, verbose_name="مفتوح للتصويت"),
                ),
                (
                    "closes_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="يُغلق في"
                    ),
                ),
                (
                    "show_results_before_vote",
                    models.BooleanField(
                        default=False,
                        help_text="افتراضياً تظهر النتائج بعد التصويت أو بعد الإغلاق.",
                        verbose_name="إظهار النتائج قبل التصويت",
                    ),
                ),
                ("total_votes", models.PositiveIntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "استطلاع",
                "verbose_name_plural": "الاستطلاعات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=150, verbose_name="الخيار")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("votes", models.PositiveIntegerField(default=0)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="polls.poll",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
    ]
