# Generated by Django 5.2.17 on 2026-09-28 18:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("beat_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("info", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="AdSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="الاسم")),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("header", "أعلى الصفحة"),
                            ("sidebar", "الشريط الجانبي"),
                            ("article_inline", "داخل المقال"),
                            ("article_end", "نهاية المقال"),
                            ("home", "بين كتل الرئيسية"),
                        ],
                        max_length=20,
                        verbose_name="المكان",
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="رابط الإعلان")),
                (
                    "html",
                    models.TextField(
                        blank=True,
                        help_text="تُستخدم بدلاً من الصورة إن وُجدت.",
                        verbose_name="شيفرة الإعلان",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="يبدأ"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ينتهي"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.mediaasset",
                        verbose_name="صورة الإعلان",
                    ),
                ),
            ],
            options={
                "verbose_name": "مساحة إعلانية",
                "verbose_name_plural": "المساحات الإعلانية",
            },
        ),
        migrations.CreateModel(
            name="HomeBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hero", "الواجهة (خبر رئيسي وأخبار جانبية)"),
                            ("latest", "آخر الأخبار"),
                            ("category", "قسم"),
                            ("columns", "أعمدة أقسام متجاورة"),
                            ("most_read", "الأكثر قراءة"),
                            ("opinion", "مقالات الرأي"),
                            ("video", "شريط الفيديو"),
                            ("kind", "نوع مادة (إنفوجراف، تقارير...)"),
                            ("dossier", "ملف خاص"),
                            ("live", "التغطية المباشرة الجارية"),
                            ("newsletter", "الاشتراك في النشرة"),
                            ("ad", "مساحة إعلانية"),
                            ("html", "محتوى حر"),
                        ],
                        max_length=20,
                        verbose_name="نوع الكتلة",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="العنوان الظاهر"
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("grid", "شبكة بطاقات"),
                            ("feature", "مادة كبيرة وقائمة"),
                            ("list", "قائمة مضغوطة"),
                            ("strip", "شريط أفقي"),
                        ],
                        default="grid",
                        max_length=10,
                        verbose_name="التخطيط",
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="عدد المواد"
                    ),
                ),
                (
                    "article_kind",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="نوع المادة"
                    ),
                ),
                ("html", models.TextField(blank=True, verbose_name="المحتوى الحر")),
                (
                    "dark",
                    models.BooleanField(default=False, verbose_name="خلفية داكنة"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
                (
                    "ad_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.adslot",
                        verbose_name="الإعلان",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="content.category",
                        verbose_name="الأقسام (للأعمدة)",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.category",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.dossier",
                        verbose_name="الملف",
                    ),
                ),
            ],
            options={
                "verbose_name": "كتلة رئيسية",
                "verbose_name_plural": "كتل الصفحة الرئيسية",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=60)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "في الانتظار"),
                            ("running", "قيد التنفيذ"),
                            ("done", "تمت"),
                            ("failed", "فشلت"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "run_after",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                ("locked_by", models.CharField(blank=True, max_length=80)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["run_after", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "run_after"],
                        name="core_job_status_df1a33_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("main", "القائمة الرئيسية"),
                            ("top", "الشريط العلوي"),
                            ("footer", "التذييل"),
                        ],
                        default="main",
                        max_length=10,
                        verbose_name="الموقع",
                    ),
                ),
                ("label", models.CharField(max_length=60, verbose_name="النص")),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("category", "قسم"),
                            ("kind", "نوع مادة"),
                            ("dossier", "ملف خاص"),
                            ("page", "صفحة ثابتة"),
                            ("tag", "وسم"),
                            ("live", "التغطيات المباشرة"),
                            ("url", "رابط"),
                        ],
                        default="category",
                        max_length=10,
                        verbose_name="نوع الرابط",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="نوع المادة"
                    ),
                ),
                (
                    "url",
                    models.CharField(blank=True, max_length=300, verbose_name="الرابط"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "highlight",
                    models.BooleanField(default=False, verbose_name="تمييز بلون"),
                ),
                (
                    "new_tab",
                    models.BooleanField(
                        default=False, verbose_name="فتح في نافذة جديدة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.category",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.dossier",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.menuitem",
                        verbose_name="تحت عنصر",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر قائمة",
                "verbose_name_plural": "القوائم",
                "ordering": ["location", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="زاجل الإخبارية",
                        max_length=120,
                        verbose_name="اسم الموقع",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        default="زاجل", max_length=40, verbose_name="الاسم المختصر"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="الصورة الكاملة، من الميدان",
                        max_length=200,
                        verbose_name="الشعار النصي",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="شبكة إخبارية عربية مستقلة تغطي الأحداث على مدار الساعة.",
                        verbose_name="وصف الموقع (لمحركات البحث)",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#b0101c",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "اكتب اللون بصيغة \u200e#RRGGBB\u200e",
                            )
                        ],
                        verbose_name="اللون الرئيسي",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#111418",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "اكتب اللون بصيغة \u200e#RRGGBB\u200e",
                            )
                        ],
                        verbose_name="لون التمييز",
                    ),
                ),
                (
                    "header_dark",
                    models.BooleanField(default=False, verbose_name="ترويسة داكنة"),
                ),
                (
                    "font_headings",
                    models.CharField(
                        choices=[
                            ("plex", "IBM Plex Sans Arabic (عصري)"),
                            ("kufi", "Noto Kufi Arabic (كوفي عريض)"),
                            ("naskh", "Noto Naskh Arabic (نسخ صحفي)"),
                        ],
                        default="plex",
                        max_length=10,
                        verbose_name="خط العناوين",
                    ),
                ),
                (
                    "font_body",
                    models.CharField(
                        choices=[
                            ("plex", "IBM Plex Sans Arabic (عصري)"),
                            ("kufi", "Noto Kufi Arabic (كوفي عريض)"),
                            ("naskh", "Noto Naskh Arabic (نسخ صحفي)"),
                        ],
                        default="naskh",
                        max_length=10,
                        verbose_name="خط المتن",
                    ),
                ),
                (
                    "month_style",
                    models.CharField(
                        choices=[
                            ("dual", "مزدوج: أيلول/سبتمبر"),
                            ("levant", "شامي: أيلول"),
                            ("egypt", "مصري وخليجي: سبتمبر"),
                            ("morocco", "مغربي: شتنبر"),
                            ("algeria", "جزائري وتونسي: سبتمبر/جانفي"),
                        ],
                        default="dual",
                        max_length=10,
                        verbose_name="أسماء الأشهر",
                    ),
                ),
                (
                    "digits",
                    models.CharField(
                        choices=[("latin", "0123456789"), ("arabic", "٠١٢٣٤٥٦٧٨٩")],
                        default="latin",
                        max_length=10,
                        verbose_name="رسم الأرقام",
                    ),
                ),
                (
                    "clock",
                    models.CharField(
                        choices=[("12", "12 ساعة"), ("24", "24 ساعة")],
                        default="12",
                        max_length=2,
                        verbose_name="نظام الساعة",
                    ),
                ),
                (
                    "show_hijri",
                    models.BooleanField(
                        default=True, verbose_name="إظهار التاريخ الهجري"
                    ),
                ),
                (
                    "hijri_adjust",
                    models.SmallIntegerField(
                        default=0, verbose_name="تعديل الهجري (أيام)"
                    ),
                ),
                (
                    "ticker_enabled",
                    models.BooleanField(default=True, verbose_name="تفعيل شريط العاجل"),
                ),
                (
                    "ticker_label",
                    models.CharField(
                        default="عاجل", max_length=20, verbose_name="عنوان الشريط"
                    ),
                ),
                (
                    "ticker_hours",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="مدة بقاء العاجل (ساعات)"
                    ),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="فيسبوك")),
                ("x_twitter", models.URLField(blank=True, verbose_name="إكس (تويتر)")),
                ("instagram", models.URLField(blank=True, verbose_name="إنستغرام")),
                ("youtube", models.URLField(blank=True, verbose_name="يوتيوب")),
                ("telegram", models.URLField(blank=True, verbose_name="تيليجرام")),
                ("whatsapp", models.URLField(blank=True, verbose_name="قناة واتساب")),
                ("tiktok", models.URLField(blank=True, verbose_name="تيك توك")),
                (
                    "alt_language_label",
                    models.CharField(
                        blank=True,
                        default="English",
                        max_length=30,
                        verbose_name="رابط لغة أخرى (النص)",
                    ),
                ),
                (
                    "alt_language_url",
                    models.URLField(blank=True, verbose_name="رابط لغة أخرى"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="بريد التواصل"
                    ),
                ),
                (
                    "tips_note",
                    models.CharField(
                        blank=True,
                        default="لإرسال معلومة أو صورة بأمان، تواصل معنا عبر تيليجرام أو سيغنال. ننزع البيانات المخفية من كل صورة قبل نشرها.",
                        max_length=300,
                        verbose_name="ملاحظة لمرسلي المعلومات",
                    ),
                ),
                (
                    "footer_about",
                    models.TextField(
                        blank=True, default="", verbose_name="نبذة التذييل"
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True,
                        default="جميع الحقوق محفوظة",
                        max_length=200,
                        verbose_name="نص الحقوق",
                    ),
                ),
                (
                    "require_2fa_all_staff",
                    models.BooleanField(
                        default=True,
                        help_text="مفروض دائماً على المحررين ومن فوقهم؛ هذا الخيار يمدّه إلى المراسلين والكتّاب.",
                        verbose_name="فرض التحقق الثنائي على كل الطاقم",
                    ),
                ),
                (
                    "require_review",
                    models.BooleanField(
                        default=True,
                        help_text="يمنع رئيس القسم من نشر مادته دون مراجعة زميل.",
                        verbose_name="إلزام المراجعة قبل النشر",
                    ),
                ),
                (
                    "analytics_enabled",
                    models.BooleanField(default=True, verbose_name="قياس الجمهور"),
                ),
                (
                    "analytics_respect_dnt",
                    models.BooleanField(
                        default=True, verbose_name="احترام «عدم التتبع» في المتصفح"
                    ),
                ),
                (
                    "newsletter_enabled",
                    models.BooleanField(default=True, verbose_name="النشرة اليومية"),
                ),
                (
                    "newsletter_hour",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="ساعة إرسال النشرة"
                    ),
                ),
                (
                    "newsletter_count",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="عدد مواد النشرة"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="الإشعارات الفورية في المتصفح"
                    ),
                ),
                (
                    "home_cache_seconds",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="تخزين الرئيسية مؤقتاً (ثوانٍ)"
                    ),
                ),
                (
                    "custom_head_html",
                    models.TextField(
                        blank=True,
                        help_text="لأكواد التحقق أو الإعلانات. تُضاف كما هي؛ لا تضع هنا أي متتبع لطرف ثالث إلا عن قصد.",
                        verbose_name="شيفرة إضافية في الترويسة",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_share_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.mediaasset",
                        verbose_name="صورة المشاركة الافتراضية",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.mediaasset",
                        verbose_name="الشعار",
                    ),
                ),
                (
                    "logo_dark",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.mediaasset",
                        verbose_name="الشعار للوضع الداكن",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
                "verbose_name_plural": "إعدادات الموقع",
            },
        ),
    ]
