# Generated by Django 5.2.17 on 2026-09-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="tips_enabled",
            field=models.BooleanField(
                default=True,
                help_text="صفحة يرسل منها المصادر معلومات وصوراً دون كشف هويتهم، ويطّلع عليها رئيس التحرير ومدير النظام فقط.",
                verbose_name="صندوق المعلومات الآمن",
            ),
        ),
    ]
