# Generated by Django 5.2.17 on 2026-09-28 21:09

import django.db.models.deletion
from django.db import migrations, models


def dark_to_background(apps, schema_editor):
    HomeBlock = apps.get_model("core", "HomeBlock")
    HomeBlock.objects.filter(dark=True).update(background="dark")


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_article_audio_alter_article_kind"),
        ("core", "0003_sitesettings_tips_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeblock",
            name="background",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "بلا خلفية"),
                    ("muted", "رمادية فاتحة"),
                    ("dark", "داكنة"),
                    ("primary", "بلون الموقع"),
                ],
                default="",
                max_length=10,
                verbose_name="خلفية الكتلة",
            ),
        ),
        migrations.AddField(
            model_name="homeblock",
            name="button_label",
            field=models.CharField(blank=True, max_length=60, verbose_name="نص الزر"),
        ),
        migrations.AddField(
            model_name="homeblock",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="content.mediaasset",
                verbose_name="الصورة",
            ),
        ),
        migrations.AddField(
            model_name="homeblock",
            name="items",
            field=models.TextField(
                blank=True,
                help_text="سطر لكل عنصر. للأرقام: القيمة | الوصف (مثل: 84493+ | خبر منشور). للمنصات: اسم المنصة | عدد المتابعين (مثل: telegram | 1.2 مليون).",
                verbose_name="العناصر",
            ),
        ),
        migrations.AddField(
            model_name="homeblock",
            name="link",
            field=models.CharField(blank=True, max_length=300, verbose_name="الرابط"),
        ),
        migrations.AddField(
            model_name="homeblock",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="سطر تعريفي"
            ),
        ),
        migrations.AddField(
            model_name="homeblock",
            name="text",
            field=models.TextField(blank=True, verbose_name="نص"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="app_android_url",
            field=models.URLField(
                blank=True, verbose_name="تطبيق Android (Google Play)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="app_ios_url",
            field=models.URLField(blank=True, verbose_name="تطبيق iPhone (App Store)"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="corner_style",
            field=models.CharField(
                choices=[
                    ("sharp", "حادة"),
                    ("soft", "مدوّرة قليلاً"),
                    ("round", "مدوّرة"),
                ],
                default="soft",
                max_length=10,
                verbose_name="زوايا البطاقات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_cta_label",
            field=models.CharField(
                blank=True,
                help_text="مثل: أرسل خبراً، تبرّع، البث المباشر",
                max_length=40,
                verbose_name="زر في الترويسة",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_cta_url",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="رابط الزر"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_style",
            field=models.CharField(
                choices=[
                    ("classic", "كلاسيكي: الشعار ثم شريط قائمة ملوّن"),
                    ("compact", "حديث: الشعار والقائمة في سطر واحد"),
                ],
                default="classic",
                max_length=10,
                verbose_name="شكل الترويسة",
            ),
        ),
        migrations.AlterField(
            model_name="homeblock",
            name="kind",
            field=models.CharField(
                choices=[
                    ("hero", "الواجهة (خبر رئيسي وأخبار جانبية)"),
                    ("latest", "آخر الأخبار"),
                    ("category", "قسم"),
                    ("columns", "أعمدة أقسام متجاورة"),
                    ("most_read", "الأكثر قراءة"),
                    ("opinion", "مقالات الرأي"),
                    ("video", "شريط الفيديو"),
                    ("kind", "نوع مادة (إنفوجراف، تقارير...)"),
                    ("dossier", "ملف خاص"),
                    ("live", "التغطية المباشرة الجارية"),
                    ("brief", "موجز الأخبار (صوتي ونصي)"),
                    ("picks", "مختارات المحررين"),
                    ("promo", "بطاقة ترويجية (قناة، تطبيق، حملة) مع رمز QR"),
                    ("stats", "أرقام وإحصاءات"),
                    ("platforms", "منصاتنا على التواصل"),
                    ("newsletter", "الاشتراك في النشرة"),
                    ("ad", "مساحة إعلانية"),
                    ("html", "محتوى حر"),
                ],
                max_length=20,
                verbose_name="نوع الكتلة",
            ),
        ),
        migrations.AlterField(
            model_name="homeblock",
            name="layout",
            field=models.CharField(
                choices=[
                    ("grid", "شبكة بطاقات"),
                    ("feature", "مادة كبيرة وقائمة"),
                    ("list", "قائمة مضغوطة"),
                    ("strip", "شريط أفقي"),
                    ("carousel", "شريط متحرك (بطاقات)"),
                    ("overlay", "شريط متحرك (العنوان على الصورة)"),
                    ("reels", "فيديو عمودي قصير"),
                ],
                default="grid",
                max_length=10,
                verbose_name="التخطيط",
            ),
        ),
        migrations.CreateModel(
            name="HomeBlockArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="content.article",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.homeblock"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("block", "article")},
            },
        ),
        migrations.AddField(
            model_name="homeblock",
            name="articles",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                through="core.HomeBlockArticle",
                to="content.article",
                verbose_name="المواد المختارة",
            ),
        ),
        migrations.RunPython(dark_to_background, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="homeblock",
            name="dark",
        ),
    ]
