# Generated by Django 5.2.17 on 2026-09-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_homeblock_styles_and_new_kinds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="font_body",
            field=models.CharField(
                choices=[
                    ("plex", "IBM Plex Sans Arabic (عصري)"),
                    ("kufi", "Noto Kufi Arabic (كوفي عريض)"),
                    ("naskh", "Noto Naskh Arabic (نسخ صحفي)"),
                    ("cairo", "Cairo (هندسي حديث)"),
                    ("tajawal", "Tajawal (خفيف واضح)"),
                    ("almarai", "Almarai (بسيط للشاشات)"),
                    ("amiri", "Amiri (نسخ كلاسيكي للمقالات)"),
                ],
                default="naskh",
                max_length=10,
                verbose_name="خط المتن",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="font_headings",
            field=models.CharField(
                choices=[
                    ("plex", "IBM Plex Sans Arabic (عصري)"),
                    ("kufi", "Noto Kufi Arabic (كوفي عريض)"),
                    ("naskh", "Noto Naskh Arabic (نسخ صحفي)"),
                    ("cairo", "Cairo (هندسي حديث)"),
                    ("tajawal", "Tajawal (خفيف واضح)"),
                    ("almarai", "Almarai (بسيط للشاشات)"),
                    ("amiri", "Amiri (نسخ كلاسيكي للمقالات)"),
                ],
                default="plex",
                max_length=10,
                verbose_name="خط العناوين",
            ),
        ),
    ]
