# Generated by Django 5.2.17 on 2026-09-29 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_more_fonts"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="breaking_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "اكتب اللون بصيغة \u200e#RRGGBB\u200e"
                    )
                ],
                verbose_name="شارة العاجل",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "اكتب اللون بصيغة \u200e#RRGGBB\u200e"
                    )
                ],
                verbose_name="التذييل",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "اكتب اللون بصيغة \u200e#RRGGBB\u200e"
                    )
                ],
                verbose_name="خلفية الترويسة",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="link_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "اكتب اللون بصيغة \u200e#RRGGBB\u200e"
                    )
                ],
                verbose_name="الروابط داخل المقالات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "اكتب اللون بصيغة \u200e#RRGGBB\u200e"
                    )
                ],
                verbose_name="شريط القائمة",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="page_color",
            field=models.CharField(
                blank=True,
                help_text="لون فاتح؛ الوضع الداكن مستقل.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "اكتب اللون بصيغة \u200e#RRGGBB\u200e"
                    )
                ],
                verbose_name="خلفية الصفحة",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="primary_dark_mode",
            field=models.CharField(
                blank=True,
                help_text="تلقائياً يُفتَّح اللون الرئيسي حتى يُقرأ على الخلفية الداكنة.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "اكتب اللون بصيغة \u200e#RRGGBB\u200e"
                    )
                ],
                verbose_name="اللون الرئيسي في الوضع الداكن",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="topbar_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "اكتب اللون بصيغة \u200e#RRGGBB\u200e"
                    )
                ],
                verbose_name="الشريط العلوي",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="accent_color",
            field=models.CharField(
                default="#111418",
                help_text="لون داكن مرافق: الشريط العلوي والتذييل والكتل الداكنة.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "اكتب اللون بصيغة \u200e#RRGGBB\u200e"
                    )
                ],
                verbose_name="اللون الثانوي",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="primary_color",
            field=models.CharField(
                default="#b0101c",
                help_text="لون الهوية: الأزرار والتسميات وعناوين الأقسام وشريط القائمة.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "اكتب اللون بصيغة \u200e#RRGGBB\u200e"
                    )
                ],
                verbose_name="اللون الرئيسي",
            ),
        ),
    ]
