# Generated by Django 5.2.17 on 2026-09-29 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_brand_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="logo_height",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="صفر = تلقائي. الشعارات العريضة تحتاج ارتفاعاً أقل، والمربعة أو ذات السطرين أكثر (بين 32 و120).",
                validators=[django.core.validators.MaxValueValidator(120)],
                verbose_name="ارتفاع الشعار في الترويسة (بكسل)",
            ),
        ),
    ]
