# Generated by Django 5.2.17 on 2026-09-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_logo_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="share_cards",
            field=models.BooleanField(
                default=True,
                help_text="صورة بالعنوان وشعار الموقع وألوانه تظهر عند مشاركة الروابط، وتُرسل مع المادة والعاجل إلى تيليجرام.",
                verbose_name="بطاقات المشاركة بهوية الموقع",
            ),
        ),
    ]
