# Generated by Django 5.2.17 on 2026-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_share_cards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeblock",
            name="kind",
            field=models.CharField(
                choices=[
                    ("hero", "الواجهة (خبر رئيسي وأخبار جانبية)"),
                    ("latest", "آخر الأخبار"),
                    ("category", "قسم"),
                    ("columns", "أعمدة أقسام متجاورة"),
                    ("most_read", "الأكثر قراءة"),
                    ("opinion", "مقالات الرأي"),
                    ("video", "شريط الفيديو"),
                    ("kind", "نوع مادة (إنفوجراف، تقارير...)"),
                    ("dossier", "ملف خاص"),
                    ("live", "التغطية المباشرة الجارية"),
                    ("brief", "موجز الأخبار (صوتي ونصي)"),
                    ("picks", "مختارات المحررين"),
                    ("promo", "بطاقة ترويجية (قناة، تطبيق، حملة) مع رمز QR"),
                    ("stats", "أرقام وإحصاءات"),
                    ("platforms", "منصاتنا على التواصل"),
                    ("newsletter", "الاشتراك في النشرة"),
                    ("poll", "استطلاع القرّاء (آخر استطلاع مفتوح)"),
                    ("ad", "مساحة إعلانية"),
                    ("html", "محتوى حر"),
                ],
                max_length=20,
                verbose_name="نوع الكتلة",
            ),
        ),
    ]
