# Generated by Django 5.2.17 on 2026-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_poll_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="style_disabled",
            field=models.JSONField(
                blank=True, default=list, verbose_name="فحوص الأسلوب المعطلة"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="style_rules",
            field=models.TextField(
                blank=True,
                help_text="سطر لكل قاعدة: «الخطأ => الصواب | ملاحظة». بلا بديل تصبح تنبيهاً فقط.",
                verbose_name="دليل الأسلوب",
            ),
        ),
    ]
