# Generated by Django 5.2.17 on 2026-09-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_style_guide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="home_cache_seconds",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="الصفحة تُبنى مرة وتُقدَّم جاهزة لكل القرّاء هذه المدة، وتتجدد فور النشر أو التعديل. 0 يوقف التخزين (لا يُنصح به: خبر عاجل واحد يكفي لإبطاء الموقع).",
                verbose_name="تخزين صفحات القرّاء (ثوانٍ)",
            ),
        ),
    ]
