# Generated by Django 5.2.17 on 2026-09-28 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySalt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True)),
                ("salt", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="DailySiteStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("visitors", models.PositiveIntegerField(default=0)),
                ("by_source", models.JSONField(default=dict)),
                ("by_device", models.JSONField(default=dict)),
                ("by_referrer", models.JSONField(default=dict)),
                ("by_category", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("path", models.CharField(max_length=300)),
                (
                    "article_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("category_id", models.BigIntegerField(blank=True, null=True)),
                ("visitor", models.CharField(db_index=True, max_length=16)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct", "مباشر"),
                            ("search", "محركات البحث"),
                            ("social", "مواقع التواصل"),
                            ("messaging", "تطبيقات المراسلة"),
                            ("internal", "تصفح داخلي"),
                            ("referral", "مواقع أخرى"),
                            ("push", "الإشعارات"),
                            ("newsletter", "النشرة البريدية"),
                        ],
                        default="direct",
                        max_length=12,
                    ),
                ),
                ("referrer_host", models.CharField(blank=True, max_length=120)),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("mobile", "هاتف"),
                            ("tablet", "لوحي"),
                            ("desktop", "حاسوب"),
                        ],
                        default="desktop",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ts", "article_id"], name="analytics_p_ts_2dc24b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyArticleStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("visitors", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="content.article",
                    ),
                ),
            ],
            options={
                "unique_together": {("day", "article")},
            },
        ),
    ]
