# Generated by Django 5.2.17 on 2026-09-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("query", models.CharField(max_length=120)),
                ("sample", models.CharField(max_length=120)),
                ("searches", models.PositiveIntegerField(default=0)),
                ("results", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("day", "query")},
            },
        ),
    ]
